spring:
  application:
    name: mock-mate-backend
  
  datasource:
    url: jdbc:mysql://localhost:3306/mockmate?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Ridd@sql9}
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            
  security:
    jwt:
      secret: ${JWT_SECRET:mockmate-secret-key-that-is-very-long-and-secure}
      expiration: ${JWT_EXPIRATION:86400000} # 24 hours
      
  cors:
    allowed-origins: ${CORS_ORIGINS:http://localhost:3000}
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true

server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

logging:
  level:
    com.mockmate: DEBUG
    org.springframework.security: DEBUG
